"""
Pydantic models for data validation and serialization.

This module defines the schema for:
- Lead qualification output
- API requests/responses
- Agent state
"""

from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field, field_validator


class OwnerType(str, Enum):
    """Type of property owner."""
    CORRETOR = "corretor"
    PROPRIETARIO = "proprietario"


class NextStep(str, Enum):
    """Next action to take with the lead."""
    AGENDAR_REUNIAO = "agendar_reuniao"
    ENVIAR_ESTUDO = "enviar_estudo"
    DISQUALIFIED = "disqualified"


class Location(BaseModel):
    """Geographic location of the property."""
    bairro: str = Field(..., description="Neighborhood name")
    cidade: str = Field(default="Florianópolis", description="City name")
    
    @field_validator('bairro')
    @classmethod
    def capitalize_bairro(cls, v: str) -> str:
        """Normalize bairro capitalization."""
        return v.strip().title()


class LeadQualification(BaseModel):
    """
    Lead qualification result schema.
    
    This is the final structured output generated by the Terra agent.
    """
    lead_qualified: bool = Field(
        ...,
        description="Whether the lead meets qualification criteria"
    )
    owner_type: OwnerType = Field(
        ...,
        description="Type of property owner (broker or owner)"
    )
    location: Location = Field(
        ...,
        description="Property location details"
    )
    land_size_m2: float = Field(
        ...,
        gt=0,
        description="Land size in square meters"
    )
    asking_price: float = Field(
        ...,
        gt=0,
        description="Asking price in BRL"
    )
    legal_status: str = Field(
        ...,
        description="Legal documentation status (escritura pública)"
    )
    obs: Optional[str] = Field(
        None,
        description="Additional observations or differentials (vista mar, etc)"
    )
    next_step: NextStep = Field(
        ...,
        description="Recommended next action"
    )
    
    class Config:
        json_schema_extra = {
            "example": {
                "lead_qualified": True,
                "owner_type": "corretor",
                "location": {
                    "bairro": "Campeche",
                    "cidade": "Florianópolis"
                },
                "land_size_m2": 450.0,
                "asking_price": 850000.0,
                "legal_status": "Sim, possui escritura pública",
                "obs": "Terreno com vista mar parcial",
                "next_step": "agendar_reuniao"
            }
        }


class ChatMessage(BaseModel):
    """Single chat message."""
    role: str = Field(..., description="Message role: 'user' or 'assistant'")
    content: str = Field(..., description="Message content")


class ChatRequest(BaseModel):
    """API request for chat interaction."""
    message: str = Field(..., min_length=1, description="User message")
    conversation_id: Optional[str] = Field(None, description="Conversation ID for tracking")


class ChatResponse(BaseModel):
    """API response for chat interaction."""
    response: str = Field(..., description="Agent response")
    conversation_id: str = Field(..., description="Conversation ID")
    qualification_complete: bool = Field(
        default=False,
        description="Whether qualification is complete"
    )
    qualification_result: Optional[LeadQualification] = Field(
        None,
        description="Final qualification result (only if complete)"
    )